### ISSUE TITLE
Release of filtering code

### ISSUE THREAD

**Issue by algvr** [epic-kitchens/epic-fields-code#1]
Dear authors, thank you for your amazing work!

Are there any plans to release the code used to perform the "filtering" step described in your work, such that out-of-dataset videos can also be processed into point clouds using your method? If so, when is the code expected to be released?

Thank you in advance!

**Comment by dimadamen** [comment]
Yes of course, There are plans but nothing during the summer. I'd say October is a more reasonable expectation for this.

**Comment by relh** [comment]
I'll post the version I wrote separately later today when I'm at my computer and maybe you can use that for now~
