### ISSUE TITLE
Distortion

### ISSUE THREAD

**Issue by ray8828** [epic-kitchens/epic-fields-code#2]
Hi, thanks for sharing this great work and data. I'm trying to run dynamic rendering on the given data, but I'm wondering whether the provided raw colormap data has distortion or not. How can i get the undistored images for rendering rays, thanks!

**Comment by zhifanzhu** [comment]
Hi👋! The majority of EPIC Kitchens videos were collected with GoPro's Linear Mode, hence we've only used OPENCV model for Colmap and distortion is considered minimal. Despite that, I believe you can still do undistortion using raw colmap data. If you download the [sparse reconstruction](https://www.dropbox.com/sh/zstt3hg0evsbpdd/AAAK4wANwtrl_Kxa03c4oTdLa?dl=0), and execute Colmap's `image_undistorter`, you should be able to get undistorted images. (See https://colmap.github.io/cli.html)

@dichotomies Feel free to add details.

**Comment by dichotomies** [comment]
Hi @ray8828, thanks for reaching out. As @zhifanzhu correctly mentioned, you can simply undistort the reconstructions with COLMAP. This should improve the rendering. Alternatively, we have now published the code for training the EPIC Fields models and inferring with them [here](https://github.com/dichotomies/epic-fields-rendering). This should give you the desired results.
