### ISSUE TITLE
Dense point cloud in the header image

### ISSUE THREAD

**Issue by zdwww** [epic-kitchens/epic-fields-code#3]
Hi! While your work and dataset are truly inspiring, I'm wondering how can we obtain the _very dense_ point cloud (illustrated in the header image, the paper's figure1 or the video you posted) from either sparse reconstruction or dense registration in COLMAP. Either the sparse/dense raw data you made available is far more sparse than in the figure.

I will be more than appreciated if you could illustrate the process since a vivid and expressive point cloud background can be truly helpful in all ways.

Thank you!

**Comment by zhifanzhu** [comment]
Hi!👋 Thanks for the interest.

To get the dense point cloud, you'll need to download the sparse COLMAP data [link](https://www.dropbox.com/scl/fo/0wtphqqyp4fu6bd7dhbfs/h?rlkey=ju21graeixi6vpecrf7rqurpt&dl=0), then run COLMAP's `image_undistorter`, `patch_match_stereo` and `stereo_fusion`.

```bash
# Place the epic-kitchens frames in $DATASET_PATH/images, 
# i.e. $DATASET_PATH/images/{frame_0000000001.jpg, ...}, 
# image resolution should be 456x256.

$ mkdir $DATASET_PATH/dense

$ colmap image_undistorter \
    --image_path $DATASET_PATH/images \
    --input_path $DATASET_PATH/sparse/0 \
    --output_path $DATASET_PATH/dense \
    --output_type COLMAP \
    --max_image_size 2000

$ colmap patch_match_stereo \
    --workspace_path $DATASET_PATH/dense \
    --workspace_format COLMAP \
    --PatchMatchStereo.geom_consistency true

$ colmap stereo_fusion \
    --workspace_path $DATASET_PATH/dense \
    --workspace_format COLMAP \
    --input_type geometric \
    --output_path $DATASET_PATH/dense/fused.ply
```

The `patch_match_stereo` step can take up to ~20hrs for one video.

Explanation of the commands can be found in COLMAP's [faq](https://colmap.github.io/faq.html) and [cli](https://colmap.github.io/cli.html).

**Comment by zdwww** [comment]
Thank you so much for your illustration! This's very helpful.

**Comment by JudyYe** [comment]
Hi team,

Great work! Congratulations! 

Could you please explain the relation between the colmap commands above and the raw COLMAP format from EPIC-FIELDS website? More specifically, the two links on the website the output or the input to the 3 colmap commands? Thanks! 

> The dense registered frames in raw COLMAP format can be found at: [here (133G)](https://www.dropbox.com/scl/fo/8li0s3fku8aeaeymd7vqr/h?rlkey=oalzl6cw877d71ljun2ai6iwm&dl=0).
The sparse frames including raw COLMAP database can be found at: [here (91.6G)](https://www.dropbox.com/scl/fo/0wtphqqyp4fu6bd7dhbfs/h?rlkey=ju21graeixi6vpecrf7rqurpt&dl=0).

**Comment by dimadamen** [comment]
As answered [elsewhere ](https://github.com/epic-kitchens/epic-fields-code/issues/7#issuecomment-1931237735)
