### ISSUE TITLE
 Details of how to integrate single-image 3D hands into EPIC-Fields

### ISSUE THREAD

**Issue by junyaoshi** [epic-kitchens/epic-fields-code#4]
Hi! I want to reproduce the single-image 3D hands (FrankMocap) integration in EPIC-Fields visualization, as shown in the bottom row of Figure 2 of the paper "EPIC Fields: Marrying 3D Geometry and Video Understanding". 

Do you guys plan to release the code for producing this visualization?

Also, it would be helpful if you can share some details of how you achieved the integration. FrankMocap produces 3D hand pose in either the SMPL coordinate or the image coordinate (where depth is ambiguous). What method did you guys use to convert FrankMocap's prediction to world coordinate? I assume that since the dataset contains camera poses in world coordinate, we can find FrankMocap's predictions in the camera coordinate, and then apply the camera2world transform. But how did you guys convert FrankMocap's predictions in SMPL coordinate or image coordinate to camera coordinate?

Many thanks in advance!

**Comment by relh** [comment]
I'm not involved but I bet that it's just an orthographic camera with scaling

**Comment by dimadamen** [comment]
Thanks for your interest. We are working on a followup on this and will be hopefully releasing code on this early next year including this visualisation,

**Comment by junyaoshi** [comment]
> I'm not involved but I bet that it's just an orthographic camera with scaling

@relh Thanks for your response! Do you mind providing a little more details about that? I believe FrankMocap assumes a weak-perspective camera, and EPIC Kitchen assumes a perspective camera. Where does orthographic camera come into play?

**Comment by junyaoshi** [comment]
> Thanks for your interest. We are working on a followup on this and will be hopefully releasing code on this early next year including this visualisation,

@dimadamen Thanks for your prompt reply! Could you please still provide answer to my other question? In particular, how did you convert FrankMocap's prediction to world coordinate in EPIC Fields? Thanks!!

**Comment by relh** [comment]
Ahh right, yes maybe weak perspective. Regardless the Z will all be the same and you probably won't be able to recover world coordinates but we should all stay tuned for the follow up!

**Comment by dimadamen** [comment]
We manually adjusted the projection (ambiguous depth) in this exact example. This was not automatically obtained.

**Comment by junyaoshi** [comment]
> We manually adjusted the projection (ambiguous depth) in this exact example. This was not automatically obtained.

@dimadamen Got it, thanks for your response!
