### ISSUE TITLE
Any existing visualization code for the "camera pose path" visualizations?

### ISSUE THREAD

**Issue by vineetparikh** [epic-kitchens/epic-fields-code#5]
I'm interested in using EPIC-Fields and wanted to examine the paths of the camera-wearer in the 3D space for a set of videos after seeing the paper and visualizations. Is there any code to replicate those visualizations directly?

**Comment by dimadamen** [comment]
What visualisations are you talking about exactly? 
Maybe your answer is in a previous response we provided [here](https://github.com/epic-kitchens/epic-fields-code/issues/3#issuecomment-1792348561)

**Comment by zhifanzhu** [comment]
> I'm interested in using EPIC-Fields and wanted to examine the paths of the camera-wearer in the 3D space for a set of videos after seeing the paper and visualizations. Is there any code to replicate those visualizations directly?

The code is now provided [here](https://github.com/epic-kitchens/epic-fields-code?tab=readme-ov-file#visualise-a-video-of-camera-poses)
