### ISSUE TITLE
Dense Camera Poses

### ISSUE THREAD

**Issue by edessa** [epic-kitchens/epic-fields-code#6]
The filtering step selects a subset of image frames for each video, over which camera poses are computed. How were the camera poses that are released under EPIC-FIELDS computed? They are far denser than would be allowed by the image selection filter.

**Comment by dimadamen** [comment]
Of course. As explained in our paper, page 4: under the title "Dense reconstruction..", after the map is built: "We then use COLMAP to register the remaining video frames to the initial reconstruction. "
So we register all remaining frames, and that's what we release.

**Comment by edessa** [comment]
Ah, I hadn't seen the image_registrator command. FYI, the dropbox link to the sparse downloads is down.

**Comment by dimadamen** [comment]
Yes thanks for letting us know. We are aware of it... our download is exceeding the daily limit at Dropbox (though we have a professional account for additional download.
We are looking at long-term alternatives, but the download should reset for tomorrow.
Apologies for the inconvenience,
